// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title ExpenseTracker
/// @notice Append-only expense logging contract supporting personal and multi-party shared ledgers on BOT Chain.
/// @dev Records are stored on-chain per wallet or per group ID and emit events for indexing.
contract ExpenseTracker {
    // -----------------------------------------------------------------
    // PERSONAL LEDGER (unchanged from v1 — do not modify)
    // -----------------------------------------------------------------

    struct Expense {
        uint256 amount;      // amount in minor units (e.g. cents) to avoid decimals
        string description;  // what the expense was for
        uint256 timestamp;   // block time the record was written
    }

    // Each wallet owns its own append-only list of expenses.
    mapping(address => Expense[]) private _expenses;

    // Running total logged per wallet (in minor units), for cheap reads.
    mapping(address => uint256) public totalSpent;

    /// @notice Emitted every time a wallet logs an expense.
    event ExpenseAdded(
        address indexed owner,
        uint256 indexed index,
        uint256 amount,
        string description,
        uint256 timestamp
    );

    /// @notice Log a new expense for the caller's wallet.
    /// @param amount Amount in minor units (e.g. cents). Must be > 0.
    /// @param description Short text describing the expense. Must not be empty.
    function addExpense(uint256 amount, string calldata description) external {
        require(amount > 0, "Amount must be greater than zero");
        require(bytes(description).length > 0, "Description required");
        require(bytes(description).length <= 200, "Description too long");

        _expenses[msg.sender].push(
            Expense(amount, description, block.timestamp)
        );
        totalSpent[msg.sender] += amount;

        emit ExpenseAdded(
            msg.sender,
            _expenses[msg.sender].length - 1,
            amount,
            description,
            block.timestamp
        );
    }

    /// @notice How many expenses a wallet has logged.
    function expenseCount(address wallet) external view returns (uint256) {
        return _expenses[wallet].length;
    }

    /// @notice Read a single expense by index for a given wallet.
    function getExpense(address wallet, uint256 index)
        external
        view
        returns (uint256 amount, string memory description, uint256 timestamp)
    {
        require(index < _expenses[wallet].length, "Index out of range");
        Expense storage e = _expenses[wallet][index];
        return (e.amount, e.description, e.timestamp);
    }

    /// @notice Read every expense a wallet has logged, newest handling left to the UI.
    /// @dev Returns the full array in one call so the frontend can render the list.
    function getExpenses(address wallet) external view returns (Expense[] memory) {
        return _expenses[wallet];
    }

    // -----------------------------------------------------------------
    // SHARED GROUP LEDGERS
    // Groups are identified by a unique client-generated bytes32 key.
    // Any wallet may append entries to an existing group ledger.
    // -----------------------------------------------------------------

    struct GroupExpense {
        address payer;        // wallet that logged this entry
        uint256 amount;       // amount in minor units (e.g. cents)
        string description;   // what the expense was for
        uint256 timestamp;    // block time the record was written
    }

    mapping(bytes32 => bool) public groupExists;
    mapping(bytes32 => string) public groupName;
    mapping(bytes32 => address) public groupCreator;
    mapping(bytes32 => uint256) public groupTotalSpent;
    mapping(bytes32 => GroupExpense[]) private _groupExpenses;

    event GroupCreated(bytes32 indexed groupId, string name, address indexed creator);
    event GroupExpenseAdded(
        bytes32 indexed groupId,
        address indexed payer,
        uint256 indexed index,
        uint256 amount,
        string description,
        uint256 timestamp
    );

    /// @notice Registers a new group ledger under a unique 32-byte identifier.
    /// @param groupId Unique bytes32 identifier generated client-side.
    /// @param name Human-readable label for the group.
    function createGroup(bytes32 groupId, string calldata name) external {
        require(!groupExists[groupId], "Group already exists");
        require(bytes(name).length > 0, "Name required");
        require(bytes(name).length <= 80, "Name too long");

        groupExists[groupId] = true;
        groupName[groupId] = name;
        groupCreator[groupId] = msg.sender;

        emit GroupCreated(groupId, name, msg.sender);
    }

    /// @notice Log an expense to a shared group ledger. Any wallet can
    ///         contribute to any existing group.
    function addGroupExpense(
        bytes32 groupId,
        uint256 amount,
        string calldata description
    ) external {
        require(groupExists[groupId], "Group does not exist");
        require(amount > 0, "Amount must be greater than zero");
        require(bytes(description).length > 0, "Description required");
        require(bytes(description).length <= 200, "Description too long");

        _groupExpenses[groupId].push(
            GroupExpense(msg.sender, amount, description, block.timestamp)
        );
        groupTotalSpent[groupId] += amount;

        emit GroupExpenseAdded(
            groupId,
            msg.sender,
            _groupExpenses[groupId].length - 1,
            amount,
            description,
            block.timestamp
        );
    }

    /// @notice Returns all recorded expenses for a specified group.
    function getGroupExpenses(bytes32 groupId) external view returns (GroupExpense[] memory) {
        return _groupExpenses[groupId];
    }

    /// @notice How many expenses a group has logged.
    function groupExpenseCount(bytes32 groupId) external view returns (uint256) {
        return _groupExpenses[groupId].length;
    }
}